adds debugger break catch
adds grep catch for "Debugger Break" in smoke_test.yml

diff --git a/.github/workflows/smoke-tests.yml b/.github/workflows/smoke-tests.yml
--- a/.github/workflows/smoke-tests.yml
+++ b/.github/workflows/smoke-tests.yml
@@ -25,6 +25,9 @@ jobs:
         run: |
           godot -d --headless --path "$PWD" -s addons/gut/gut_cmdln.gd -gdir=res://test/smoke -gexit 2>&1 | tee output.log
           if grep -q "SCRIPT ERROR:" output.log; then
-            echo "❌ Godot errors detected in log!"
+            echo "❌ Script errors detected in log!"
+            exit 1
+          if grep -q "Debugger Break" output.log; then
+            echo "❌ Debugger errors detected in log!"
             exit 1
           fi
